// Original teaching examples. Each listed word has two contextual examples.
const exampleGroups = `
1,21,36|Ich bin hier.|I am here.|Mən buradayam.|Hier bin ich zu Hause.|This is where I feel at home.|Mən burada özümü evimdəki kimi hiss edirəm.
2,20,49|Ich habe Zeit, aber ich brauche Hilfe.|I have time, but I need help.|Vaxtım var, amma köməyə ehtiyacım var.|Wir haben alles, was wir brauchen, außer Zeit.|We have everything we need except time.|Vaxtdan başqa ehtiyacımız olan hər şey var.
3,42|Das Kind wird groß.|The child is growing up.|Uşaq böyüyür.|Unser Garten wird immer größer.|Our garden is getting bigger and bigger.|Bağımız getdikcə böyüyür.
4,16,22|Du kannst gut Deutsch sprechen.|You can speak German well.|Sən almanca yaxşı danışa bilirsən.|Kannst du bitte langsamer sprechen?|Can you please speak more slowly?|Zəhmət olmasa, daha yavaş danışa bilərsən?
5,18|Ich muss heute arbeiten.|I have to work today.|Bu gün işləməliyəm.|Müssen wir morgen arbeiten?|Do we have to work tomorrow?|Sabah işləməliyik?
6,23|Er macht Kaffee.|He is making coffee.|O, qəhvə hazırlayır.|Was macht er heute?|What is he doing today?|O, bu gün nə edir?
7,24|Sie sagt, dass sie müde ist.|She says that she is tired.|O deyir ki, yorğundur.|Sie sagen immer die Wahrheit.|They always tell the truth.|Onlar həmişə həqiqəti deyirlər.
8,25,38|Wir gehen heute ins Kino.|We are going to the cinema today.|Biz bu gün kinoya gedirik.|Heute gehen wir zu Fuß.|Today we are going on foot.|Bu gün piyada gedirik.
9,37|Da kommt der Bus.|There comes the bus.|Avtobus gəlir.|Komm bitte her, da ist ein freier Platz.|Please come over; there is a free seat there.|Zəhmət olmasa, bura gəl; orada boş yer var.
10,26,48|Ich sehe das Kind.|I can see the child.|Mən uşağı görürəm.|Siehst du das Kind am Fenster?|Do you see the child by the window?|Pəncərənin yanındakı uşağı görürsən?
11,28,47|Die Frau gibt mir ein Buch.|The woman gives me a book.|Qadın mənə bir kitab verir.|Gib der Frau bitte die Tasche.|Please give the woman the bag.|Zəhmət olmasa, çantanı qadına ver.
12,35|Ich weiß es nicht.|I do not know.|Mən bunu bilmirəm.|Weißt du nicht, wo der Bahnhof ist?|Do you not know where the station is?|Vağzalın harada olduğunu bilmirsən?
13,29|Ich finde ein Café.|I find a café.|Mən bir kafe tapıram.|Wir finden ein Hotel in der Stadt.|We find a hotel in the city.|Biz şəhərdə bir otel tapırıq.
14,39|Ich bleibe jetzt zu Hause.|I am staying at home now.|Mən indi evdə qalıram.|Bleibst du jetzt hier?|Are you staying here now?|Sən indi burada qalırsan?
15,27,46|Der Mann nimmt den Bus.|The man takes the bus.|Kişi avtobusa minir.|Nimmt der Mann die Tasche mit?|Is the man taking the bag with him?|Kişi çantanı özü ilə aparır?
17,40|Ich lerne immer am Abend.|I always study in the evening.|Mən həmişə axşam dərs oxuyuram.|Wir lernen immer neue Wörter.|We always learn new words.|Biz həmişə yeni sözlər öyrənirik.
19,31|Anna und Ali wohnen in Berlin.|Anna and Ali live in Berlin.|Anna və Əli Berlində yaşayırlar.|Ich wohne hier und arbeite dort.|I live here and work there.|Mən burada yaşayıram və orada işləyirəm.
30,32|Hast du kein Geld oder keine Zeit?|Do you have no money or no time?|Pulun yoxdur, yoxsa vaxtın yoxdur?|Ist das kein Tee oder schmeckt er nur anders?|Is that not tea, or does it just taste different?|Bu çay deyil, yoxsa sadəcə dadı fərqlidir?
33,41|Das Essen ist gut, aber teuer.|The food is good but expensive.|Yemək yaxşıdır, amma bahadır.|Ich spreche gut Englisch, aber nur wenig Deutsch.|I speak English well, but only a little German.|İngiliscə yaxşı danışıram, amma almanca az bilirəm.
34,43|Meine Wohnung ist auch klein.|My apartment is small too.|Mənim mənzilim də kiçikdir.|Hast du auch einen kleinen Hund?|Do you also have a small dog?|Sənin də balaca itin var?
44,45|Mein Fahrrad ist alt, dein Fahrrad ist neu.|My bicycle is old; your bicycle is new.|Mənim velosipedim köhnədir, sənin velosipedin yenidir.|Das neue Haus steht neben dem alten Haus.|The new house stands next to the old house.|Yeni ev köhnə evin yanında yerləşir.
50|Der Tag beginnt um sieben.|The day starts at seven.|Gün saat yeddidə başlayır.|Ich lerne jeden Tag Deutsch.|I study German every day.|Mən hər gün almanca öyrənirəm.
51,98|Darf ich dich etwas fragen? Ich habe eine Frage.|May I ask you something? I have a question.|Səndən bir şey soruşa bilərəm? Bir sualım var.|Sie fragt den Lehrer, weil sie eine Frage hat.|She asks the teacher because she has a question.|Sualı olduğu üçün müəllimdən soruşur.
52,99|Er antwortet sofort, aber die Antwort ist falsch.|He answers immediately, but the answer is wrong.|O dərhal cavab verir, amma cavabı səhvdir.|Bitte antworte kurz; eine lange Antwort ist nicht nötig.|Please answer briefly; a long answer is not necessary.|Zəhmət olmasa, qısa cavab ver; uzun cavab lazım deyil.
53,93|Ich erzähle dir von meiner Familie.|I will tell you about my family.|Sənə ailəm haqqında danışacağam.|Meine Familie erzählt oft Geschichten.|My family often tells stories.|Ailəm tez-tez hekayələr danışır.
54,97|Kannst du mir das Problem erklären?|Can you explain the problem to me?|Problemi mənə izah edə bilərsən?|Sie erklärt, warum es ein Problem gibt.|She explains why there is a problem.|O, problemin niyə yarandığını izah edir.
55,75|Manchmal hilft mir mein Nachbar.|Sometimes my neighbour helps me.|Bəzən qonşum mənə kömək edir.|Ich helfe manchmal in der Küche.|I sometimes help in the kitchen.|Mən bəzən mətbəxdə kömək edirəm.
56,94|Ich zeige dir meine Wohnung.|I will show you my apartment.|Sənə mənzilimi göstərəcəyəm.|Können Sie uns die Wohnung zeigen?|Can you show us the apartment?|Bizə mənzili göstərə bilərsiniz?
57,92|Bring bitte das Geld mit.|Please bring the money with you.|Zəhmət olmasa, pulu özünlə gətir.|Ich bringe dir morgen das Geld.|I will bring you the money tomorrow.|Sabah pulu sənə gətirəcəyəm.
58,89|Ich kaufe das billige Brot.|I am buying the cheap bread.|Mən ucuz çörəyi alıram.|Wo kann man hier billig Obst kaufen?|Where can you buy fruit cheaply here?|Burada haradan ucuz meyvə almaq olar?
59,88|Das Hotel ist teuer, aber ich bezahle die Rechnung.|The hotel is expensive, but I am paying the bill.|Otel bahadır, amma hesabı mən ödəyirəm.|Wer bezahlt das teure Essen?|Who is paying for the expensive meal?|Bahalı yeməyin pulunu kim ödəyir?
60,72|Ich warte noch auf den Bus.|I am still waiting for the bus.|Mən hələ də avtobusu gözləyirəm.|Wartest du noch auf eine Antwort?|Are you still waiting for an answer?|Sən hələ də cavab gözləyirsən?
61,71|Der Film beginnt schon um sechs.|The film starts as early as six.|Film artıq saat altıda başlayır.|Hat der Kurs schon begonnen?|Has the course already started?|Kurs artıq başlayıb?
62,91|Meine Arbeit endet um fünf.|My work ends at five.|İşim saat beşdə bitir.|Wann endet die Arbeit heute?|When does work finish today?|Bu gün iş nə vaxt bitir?
63,96|Wir fahren in die Stadt.|We are travelling into town.|Biz şəhərə gedirik.|Fährst du mit dem Bus durch die Stadt?|Are you travelling through the city by bus?|Şəhərin içindən avtobusla gedirsən?
64,86|Er läuft sehr schnell.|He runs very fast.|O, çox sürətli qaçır.|Lauf nicht so schnell!|Do not run so fast!|Bu qədər sürətli qaçma!
65,87|Ich esse langsam.|I eat slowly.|Mən yavaş yeyirəm.|Bitte iss etwas langsamer.|Please eat a little more slowly.|Zəhmət olmasa, bir az daha yavaş ye.
66,74|Ich trinke oft Tee.|I often drink tea.|Mən tez-tez çay içirəm.|Trinkst du oft Kaffee?|Do you often drink coffee?|Sən tez-tez qəhvə içirsən?
67,90|Morgen habe ich frei und schlafe lange.|Tomorrow I have a day off and will sleep late.|Sabah boş günüm var və gec oyanacağam.|An freien Tagen schläft sie länger.|On days off she sleeps longer.|Boş günlərdə o, daha çox yatır.
68,80|Wir treffen uns später.|We will meet later.|Biz sonra görüşəcəyik.|Kann ich dich später treffen?|Can I meet you later?|Səninlə sonra görüşə bilərəm?
69,95|Wir besuchen morgen die Schule.|We are visiting the school tomorrow.|Sabah məktəbə baş çəkəcəyik.|Welche Schule besucht dein Bruder?|Which school does your brother attend?|Qardaşın hansı məktəbdə oxuyur?
70,73|Ich habe meinen Schlüssel wieder vergessen.|I have forgotten my key again.|Açarımı yenə unutmuşam.|Vergiss bitte nicht wieder den Termin.|Please do not forget the appointment again.|Zəhmət olmasa, görüşü yenə unutma.
76,100|Vielleicht reise ich nächstes Jahr nach Berlin.|Perhaps I will travel to Berlin next year.|Bəlkə gələn il Berlinə səyahət edərəm.|Vielleicht bleibt sie ein Jahr hier.|Perhaps she will stay here for a year.|Bəlkə o, burada bir il qalar.
77,81|Die Prüfung ist wichtig, deshalb lerne ich.|The exam is important, so I am studying.|İmtahan vacibdir, buna görə dərs oxuyuram.|Schlaf ist wichtig, deshalb gehe ich früh ins Bett.|Sleep is important, so I go to bed early.|Yuxu vacibdir, buna görə tez yatıram.
78,79|Zuerst dusche ich, dann frühstücke ich.|First I shower, then I have breakfast.|Əvvəlcə duş qəbul edirəm, sonra səhər yeməyi yeyirəm.|Lies zuerst den Text und beantworte dann die Fragen.|Read the text first and then answer the questions.|Əvvəlcə mətni oxu, sonra suallara cavab ver.
82,83|Ist das richtig oder falsch?|Is that right or wrong?|Bu doğrudur, yoxsa səhvdir?|Die erste Antwort ist richtig, die zweite ist falsch.|The first answer is correct; the second is wrong.|Birinci cavab doğrudur, ikinci cavab səhvdir.
84,85|Diese Aufgabe ist einfach, die andere ist schwierig.|This task is easy; the other one is difficult.|Bu tapşırıq asandır, digəri çətindir.|Der Anfang ist schwierig, später wird es einfacher.|The beginning is difficult; later it gets easier.|Başlanğıc çətindir, sonra asanlaşır.
101,155|Ich denke oft an meine Zukunft.|I often think about my future.|Mən tez-tez gələcəyim haqqında düşünürəm.|Denkst du schon über deine Zukunft nach?|Are you already thinking about your future?|Artıq gələcəyin haqqında düşünürsən?
102,138|Ich glaube, er kommt wahrscheinlich morgen.|I think he will probably come tomorrow.|Məncə, o, yəqin ki, sabah gələcək.|Sie glaubt, dass es wahrscheinlich regnen wird.|She believes that it will probably rain.|O düşünür ki, yəqin yağış yağacaq.
103,152|Was meinst du? Deine Meinung ist mir wichtig.|What do you think? Your opinion matters to me.|Sən nə düşünürsən? Fikrin mənim üçün vacibdir.|Ich meine, wir sollten auch ihre Meinung hören.|I think we should hear her opinion too.|Məncə, onun da fikrini dinləməliyik.
104,166|Ich verstehe das Beispiel nicht.|I do not understand the example.|Mən nümunəni başa düşmürəm.|Mit diesem Beispiel verstehst du die Regel besser.|With this example you will understand the rule better.|Bu nümunə ilə qaydanı daha yaxşı başa düşəcəksən.
105,154|Wir entscheiden heute; die Entscheidung ist wichtig.|We are deciding today; the decision is important.|Bu gün qərar veririk; qərar vacibdir.|Bevor du dich entscheidest, denk über die Folgen deiner Entscheidung nach.|Before you decide, think about the consequences of your decision.|Qərar verməzdən əvvəl qərarının nəticələri haqqında düşün.
106,112|Ich versuche, mein Deutsch zu verbessern.|I am trying to improve my German.|Alman dilimi yaxşılaşdırmağa çalışıram.|Versuch, deine Aussprache zu verbessern.|Try to improve your pronunciation.|Tələffüzünü yaxşılaşdırmağa çalış.
107,163|Wir planen eine Reise nach Wien.|We are planning a trip to Vienna.|Biz Vyanaya səyahət planlaşdırırıq.|Planst du deine Reise allein?|Are you planning your trip alone?|Səyahətini tək planlaşdırırsan?
108,169|Ich hoffe auf eine neue Chance.|I am hoping for a new opportunity.|Yeni bir fürsətə ümid edirəm.|Wir hoffen, dass jeder eine faire Chance bekommt.|We hope that everyone gets a fair chance.|Ümid edirik ki, hər kəsə ədalətli şans veriləcək.
109,160|Ich wünsche dir gute Gesundheit.|I wish you good health.|Sənə möhkəm cansağlığı arzulayıram.|Sie wünscht sich vor allem Gesundheit.|Above all, she wishes for good health.|O, hər şeydən əvvəl cansağlığı arzulayır.
110,146|Ich fühle mich wohl und bin zufrieden.|I feel comfortable and am satisfied.|Özümü rahat hiss edirəm və məmnunam.|Fühlst du dich besser, wenn du mit deiner Arbeit zufrieden bist?|Do you feel better when you are satisfied with your work?|İşindən razı qalanda özünü daha yaxşı hiss edirsən?
111,172|Wir ändern den Plan; die Änderung gilt ab morgen.|We are changing the plan; the change applies from tomorrow.|Planı dəyişirik; dəyişiklik sabahdan qüvvədədir.|Wenn du etwas änderst, erklär bitte die Änderung.|If you change something, please explain the change.|Nəyisə dəyişsən, zəhmət olmasa, dəyişikliyi izah et.
113,171|Wir entwickeln gemeinsam eine Lösung.|We are developing a solution together.|Biz birlikdə bir həll hazırlayırıq.|Das Team hat eine neue Lösung entwickelt.|The team has developed a new solution.|Komanda yeni bir həll hazırlayıb.
114,170|Ich möchte mein Ziel erreichen.|I want to achieve my goal.|Məqsədimə çatmaq istəyirəm.|Gemeinsam erreichen wir dieses Ziel.|Together we will achieve this goal.|Birlikdə bu məqsədə çatacağıq.
115,168|Ich vermeide schwierige Situationen.|I avoid difficult situations.|Çətin vəziyyətlərdən qaçıram.|Wie können wir eine solche Situation vermeiden?|How can we avoid such a situation?|Belə bir vəziyyətin qarşısını necə ala bilərik?
116,117|Hier ist Essen erlaubt, aber Rauchen verboten.|Eating is allowed here, but smoking is prohibited.|Burada yemək yeməyə icazə verilir, amma siqaret çəkmək qadağandır.|Die Schule erlaubt Handys in der Pause und verbietet sie im Unterricht.|The school allows phones during breaks and prohibits them in class.|Məktəb fasilədə telefonlara icazə verir, dərsdə isə qadağan edir.
118,151|Aus eigener Erfahrung empfehle ich diesen Kurs.|From personal experience, I recommend this course.|Şəxsi təcrübəmə əsasən bu kursu tövsiyə edirəm.|Kannst du aus deiner Erfahrung ein gutes Buch empfehlen?|Can you recommend a good book based on your experience?|Təcrübənə əsasən yaxşı bir kitab tövsiyə edə bilərsən?
119,167|Wir erwarten morgen das Ergebnis.|We expect the result tomorrow.|Nəticəni sabah gözləyirik.|Welches Ergebnis hast du erwartet?|What result did you expect?|Hansı nəticəni gözləyirdin?
120,156|Das ist in der Vergangenheit oft passiert.|That happened often in the past.|Bu, keçmişdə tez-tez baş verirdi.|Was ist in der Vergangenheit passiert?|What happened in the past?|Keçmişdə nə baş verib?
121,158|Wir gehören alle zu dieser Gesellschaft.|We all belong to this society.|Biz hamımız bu cəmiyyətə aidik.|Zu einer Gesellschaft zu gehören, bedeutet auch, Verantwortung zu übernehmen.|Belonging to a society also means taking responsibility.|Bir cəmiyyətə aid olmaq həm də məsuliyyət daşımaq deməkdir.
122,164|Was bedeutet dieser Unterschied?|What does this difference mean?|Bu fərq nə deməkdir?|Ein kleiner Unterschied bedeutet nicht immer ein Problem.|A small difference does not always mean a problem.|Kiçik bir fərq həmişə problem demək deyil.
123,159|Diese Regel gilt auch für den Schutz der Umwelt.|This rule also applies to environmental protection.|Bu qayda ətraf mühitin qorunmasına da aiddir.|Umweltschutz gilt als gemeinsame Aufgabe.|Environmental protection is regarded as a shared task.|Ətraf mühitin qorunması ümumi vəzifə sayılır.
124,174|Mir fehlt eine wichtige Information.|I am missing an important piece of information.|Məndə vacib bir məlumat çatışmır.|Welche Informationen fehlen noch?|What information is still missing?|Hələ hansı məlumatlar çatışmır?
125,147|Ich bin bereit und schaffe das.|I am ready and can manage this.|Mən hazıram və bunun öhdəsindən gələ bilərəm.|Bist du bereit? Zusammen schaffen wir es.|Are you ready? Together we can do it.|Hazırsan? Birlikdə bacararıq.
126,127|Obwohl ich müde bin, lerne ich, während du kochst.|Although I am tired, I study while you cook.|Yorğun olsam da, sən yemək bişirərkən dərs oxuyuram.|Obwohl es regnet, gehen wir spazieren, während die anderen zu Hause bleiben.|Although it is raining, we go for a walk while the others stay home.|Yağış yağsa da, digərləri evdə qalarkən biz gəzməyə çıxırıq.
128,129|Es regnet. Außerdem ist es kalt. Trotzdem gehen wir raus.|It is raining. It is also cold. Nevertheless, we go out.|Yağış yağır. Üstəlik, hava soyuqdur. Buna baxmayaraq, çölə çıxırıq.|Der Kurs ist teuer und außerdem weit weg. Trotzdem melde ich mich an.|The course is expensive and also far away. Nevertheless, I am signing up.|Kurs bahadır və üstəlik uzaqdadır. Buna baxmayaraq, qeydiyyatdan keçirəm.
130,131|Falls du müde bist, trink keinen Kaffee, sondern ruh dich aus.|If you are tired, do not drink coffee; rest instead.|Yorğunsansa, qəhvə içmə, əvəzinə dincəl.|Falls es regnet, gehen wir nicht in den Park, sondern ins Museum.|If it rains, we will go to the museum instead of the park.|Yağış yağsa, parka deyil, muzeyə gedəcəyik.
132,133|Sobald ich ankomme, rufe ich an, damit du Bescheid weißt.|As soon as I arrive, I will call so that you know.|Çatan kimi sənə zəng edəcəyəm ki, xəbərin olsun.|Sobald der Kurs beginnt, mache ich Notizen, damit ich nichts vergesse.|As soon as the course starts, I take notes so that I do not forget anything.|Kurs başlayan kimi qeydlər aparıram ki, heç nəyi unutmayım.
134,135|Wir sprechen darüber. Bist du dafür?|We are talking about it. Are you in favour?|Biz bu barədə danışırıq. Sən bunun tərəfdarısan?|Ich denke darüber nach, ob ich dafür Zeit habe.|I am thinking about whether I have time for it.|Bunun üçün vaxtımın olub-olmadığını düşünürəm.
136,137|Eigentlich mag ich Obst, besonders Äpfel.|Actually, I like fruit, especially apples.|Əslində, meyvəni, xüsusilə almanı sevirəm.|Was findest du eigentlich besonders interessant?|What do you actually find especially interesting?|Əslində, sənə xüsusilə maraqlı gələn nədir?
139,140|Natürlich helfe ich dir; ich habe ungefähr eine Stunde Zeit.|Of course I will help you; I have about an hour.|Əlbəttə, sənə kömək edərəm; təxminən bir saat vaxtım var.|Natürlich kenne ich den Weg; er dauert ungefähr zehn Minuten.|Of course I know the way; it takes about ten minutes.|Əlbəttə, yolu bilirəm; təxminən on dəqiqə çəkir.
141,142|Wir haben unterschiedliche Ideen, arbeiten aber gemeinsam.|We have different ideas but work together.|Fərqli fikirlərimiz var, amma birlikdə işləyirik.|Gemeinsam lernen wir unterschiedliche Methoden kennen.|Together we get to know different methods.|Birlikdə fərqli üsullarla tanış oluruq.
143,144|Eine Pause ist möglich und notwendig.|A break is possible and necessary.|Fasilə vermək mümkündür və zəruridir.|Ist es möglich, nur die notwendigen Dokumente zu schicken?|Is it possible to send only the necessary documents?|Yalnız zəruri sənədləri göndərmək mümkündür?
145,149|Der Grund ist bekannt, aber die Lösung ist noch nicht klar.|The reason is known, but the solution is not yet clear.|Səbəb məlumdur, amma həll hələ aydın deyil.|Ist dir klar, warum dieser Autor so bekannt ist?|Is it clear to you why this author is so well known?|Bu müəllifin niyə bu qədər tanındığı sənə aydındır?
148,150|Es ist normal, dass du dich am Anfang nicht sicher fühlst.|It is normal not to feel confident at first.|Başlanğıcda özünü əmin hiss etməməyin normaldır.|Bist du sicher, dass dieses Geräusch normal ist?|Are you sure this noise is normal?|Bu səsin normal olduğuna əminsən?
153,175|Diese Möglichkeit hat einen großen Vorteil.|This option has a major advantage.|Bu imkanın böyük üstünlüyü var.|Ein Vorteil ist die Möglichkeit, von zu Hause zu arbeiten.|One advantage is the possibility of working from home.|Üstünlüklərdən biri evdən işləmək imkanıdır.
157,165|Vertrauen ist ein Grund für unsere gute Beziehung.|Trust is one reason for our good relationship.|Etibar yaxşı münasibətimizin səbəblərindən biridir.|Was ist der Grund für die Veränderung in eurer Beziehung?|What is the reason for the change in your relationship?|Münasibətinizdəki dəyişikliyin səbəbi nədir?
161,162,173|Meine Ausbildung bereitet mich auf einen Beruf im technischen Bereich vor.|My training prepares me for a profession in the technical field.|Peşə təhsilim məni texniki sahədə bir peşəyə hazırlayır.|Welche Ausbildung braucht man für einen Beruf in diesem Bereich?|What training do you need for a profession in this field?|Bu sahədə işləmək üçün hansı peşə təhsili lazımdır?
176,213|Soziale Medien beeinflussen unsere Entwicklung.|Social media influences our development.|Sosial media inkişafımıza təsir edir.|Wie beeinflusst Bewegung die Entwicklung von Kindern?|How does exercise influence children's development?|Fiziki hərəkət uşaqların inkişafına necə təsir edir?
177,207|Wir beurteilen, ob die Ergebnisse vergleichbar sind.|We assess whether the results are comparable.|Nəticələrin müqayisə edilə biləcəyini qiymətləndiririk.|Ohne vergleichbare Daten lässt sich der Erfolg schwer beurteilen.|Without comparable data, success is difficult to assess.|Müqayisə edilə bilən məlumatlar olmadan uğuru qiymətləndirmək çətindir.
178,212|Die Leiterin begründet die neue Maßnahme.|The manager explains the reasons for the new measure.|Rəhbər yeni tədbiri əsaslandırır.|Jede Maßnahme muss gut begründet sein.|Every measure must be well justified.|Hər bir tədbir yaxşı əsaslandırılmalıdır.
179,196|Er behauptet, alles zu wissen; allerdings macht er Fehler.|He claims to know everything; however, he makes mistakes.|O, hər şeyi bildiyini iddia edir; lakin səhvlər edir.|Sie behauptet, pünktlich zu sein, kommt allerdings oft zu spät.|She claims to be punctual but often arrives late.|O, punktual olduğunu iddia edir, lakin tez-tez gecikir.
180,205|Ich betrachte diese Reaktion als angemessen.|I consider this response appropriate.|Bu reaksiyanı münasib hesab edirəm.|Betrachten Sie diesen Preis als angemessen?|Do you consider this price reasonable?|Bu qiyməti münasib hesab edirsiniz?
181,210|Wir berücksichtigen die Wünsche der betroffenen Personen.|We take the wishes of the affected people into account.|Təsirlənmiş şəxslərin istəklərini nəzərə alırıq.|Die Planung muss alle Betroffenen berücksichtigen.|The planning must take everyone affected into account.|Planlaşdırmada bütün təsirlənmiş şəxslər nəzərə alınmalıdır.
182,203|Die Grafik stellt den Unterschied deutlich dar.|The chart presents the difference clearly.|Qrafik fərqi aydın göstərir.|Bitte stellen Sie Ihre Idee deutlicher dar.|Please present your idea more clearly.|Zəhmət olmasa, fikrinizi daha aydın təqdim edin.
183,214|Wir stellen fest, dass die Änderung positive Auswirkungen hat.|We find that the change has positive effects.|Dəyişikliyin müsbət təsirləri olduğunu müəyyən edirik.|Welche Auswirkungen haben Sie festgestellt?|What effects have you identified?|Hansı təsirləri müəyyən etmisiniz?
184,221|Das Training fördert die Fähigkeit, Probleme zu lösen.|The training develops the ability to solve problems.|Təlim problemləri həll etmək bacarığını inkişaf etdirir.|Wie können wir diese Fähigkeit fördern?|How can we develop this ability?|Bu bacarığı necə inkişaf etdirə bilərik?
185,204|Die Mitarbeitenden fordern eine erhebliche Verbesserung.|The employees demand a substantial improvement.|Əməkdaşlar əhəmiyyətli yaxşılaşma tələb edirlər.|Sie fordern erheblich mehr Zeit für das Projekt.|They demand considerably more time for the project.|Layihə üçün xeyli daha çox vaxt tələb edirlər.
186,209|Wir verfügen über drei Räume, aber nur einer ist verfügbar.|We have three rooms at our disposal, but only one is available.|İxtiyarımızda üç otaq var, amma yalnız biri boşdur.|Verfügen Sie über Informationen zu verfügbaren Wohnungen?|Do you have information about available apartments?|Boş mənzillər haqqında məlumatınız var?
187,198|Wir vergleichen die Preise: Tee ist günstig, Kaffee hingegen teuer.|We compare the prices: tea is cheap, whereas coffee is expensive.|Qiymətləri müqayisə edirik: çay ucuzdur, qəhvə isə bahadır.|Ich vergleiche die Kosten, sie hingegen vergleicht die Qualität.|I compare the costs, whereas she compares the quality.|Mən xərcləri müqayisə edirəm, o isə keyfiyyəti müqayisə edir.
188,211|Der Kurs setzt Grundkenntnisse voraus; Erfahrung ist keine Voraussetzung.|The course requires basic knowledge; experience is not a prerequisite.|Kurs ilkin bilik tələb edir; təcrübə ilkin şərt deyil.|Die Teilnahme setzt voraus, dass alle Voraussetzungen erfüllt sind.|Participation requires that all prerequisites are met.|İştirak üçün bütün ilkin şərtlərin yerinə yetirilməsi tələb olunur.
189,197|Ich verstehe deinen Punkt, dennoch widerspreche ich dir.|I understand your point; nevertheless, I disagree with you.|Fikrini başa düşürəm, buna baxmayaraq, səninlə razı deyiləm.|Die Daten widersprechen der Annahme; dennoch hält er daran fest.|The data contradicts the assumption; nevertheless, he sticks to it.|Məlumatlar fərziyyəyə ziddir; buna baxmayaraq, o, fikrindən dönmür.
190,215|Wie hängen diese Ereignisse zusammen? Der Zusammenhang ist unklar.|How are these events connected? The connection is unclear.|Bu hadisələr bir-biri ilə necə əlaqəlidir? Əlaqə aydın deyil.|Ob die Probleme zusammenhängen, zeigt sich erst im größeren Zusammenhang.|Whether the problems are connected only becomes clear in the wider context.|Problemlərin əlaqəli olub-olmadığı yalnız daha geniş kontekstdə aydın olur.
191,192|Die Nachfrage nimmt zu, während das Angebot abnimmt.|Demand increases while supply decreases.|Tələb artır, təklif isə azalır.|Im Winter nimmt die Temperatur ab, im Frühling nimmt sie wieder zu.|In winter the temperature decreases; in spring it increases again.|Qışda temperatur azalır, yazda isə yenidən artır.
193,224|Durch den Fehler entstehen zusätzliche Kosten; das ist eine unerwartete Folge.|The error creates additional costs; that is an unexpected consequence.|Səhv əlavə xərclər yaradır; bu, gözlənilməz nəticədir.|Welche Folgen entstehen, wenn wir nichts tun?|What consequences arise if we do nothing?|Heç nə etməsək, hansı nəticələr yaranar?
194,208|Das Stipendium ermöglicht ihr, unabhängig zu leben.|The scholarship enables her to live independently.|Təqaüd ona müstəqil yaşamaq imkanı verir.|Digitale Werkzeuge ermöglichen unabhängiges Lernen.|Digital tools enable independent learning.|Rəqəmsal alətlər müstəqil öyrənməyə imkan yaradır.
195,225|Der Zweck dieser Kontrolle ist, Fehler zu verhindern.|The purpose of this check is to prevent errors.|Bu yoxlamanın məqsədi səhvlərin qarşısını almaqdır.|Wir erklären den Zweck der Regel, um Missverständnisse zu verhindern.|We explain the purpose of the rule to prevent misunderstandings.|Anlaşılmazlıqların qarşısını almaq üçün qaydanın məqsədini izah edirik.
199,200|Inzwischen nutzen viele Menschen die App, insbesondere Studierende.|Many people now use the app, especially students.|Artıq bir çox insan, xüsusilə tələbələr tətbiqdən istifadə edir.|Insbesondere am Abend sind inzwischen viele Plätze besetzt.|Many seats are now occupied, especially in the evening.|Artıq bir çox yer, xüsusilə axşamlar dolu olur.
201,202|Grundsätzlich ist regelmäßiges Üben ein wesentlicher Teil des Lernens.|In general, regular practice is an essential part of learning.|Ümumiyyətlə, müntəzəm məşq öyrənmənin mühüm hissəsidir.|Wir sind grundsätzlich einverstanden, haben aber einen wesentlichen Einwand.|We agree in principle but have one significant objection.|Prinsipcə razıyıq, amma mühüm bir etirazımız var.
206,218|Wer ist für diese Regelung verantwortlich?|Who is responsible for this arrangement?|Bu qaydaya görə kim məsuliyyət daşıyır?|Die verantwortliche Person erklärt die neue Regelung.|The person responsible explains the new arrangement.|Məsul şəxs yeni qaydanı izah edir.
216,217|Verantwortung zu übernehmen, ist eine Herausforderung.|Taking responsibility is a challenge.|Məsuliyyət götürmək çətin bir vəzifədir.|Diese Herausforderung bringt viel Verantwortung mit sich.|This challenge involves a lot of responsibility.|Bu çətin vəzifə özü ilə böyük məsuliyyət gətirir.
219,222|Der Einfluss der Sprache auf das Denken ist von großer Bedeutung.|The influence of language on thinking is of great significance.|Dilin düşüncəyə təsiri böyük əhəmiyyət daşıyır.|Wir untersuchen die Bedeutung und den Einfluss sozialer Medien.|We examine the significance and influence of social media.|Sosial medianın əhəmiyyətini və təsirini araşdırırıq.
220,223|Unter welcher Bedingung besteht ein Anspruch auf Teilnahme?|Under what condition is there an entitlement to participate?|Hansı şərtlə iştirak hüququ yaranır?|Ob ein Anspruch besteht, hängt von den vereinbarten Bedingungen ab.|Whether an entitlement exists depends on the agreed conditions.|Hüququn olub-olmaması razılaşdırılmış şərtlərdən asılıdır.
226,237|Die Planung gewährleistet insofern Sicherheit, als alle Aufgaben klar verteilt sind.|The planning ensures security insofar as all tasks are clearly allocated.|Planlaşdırma bütün vəzifələrin aydın bölüşdürülməsi baxımından etibarlılığı təmin edir.|Der Test ist insofern hilfreich, als er eine gleichbleibende Qualität gewährleistet.|The test is helpful in that it ensures consistent quality.|Test sabit keyfiyyəti təmin etdiyi üçün faydalıdır.
227,249|Ich kann deine Auffassung nachvollziehen.|I can understand your view.|Sənin mövqeyini başa düşə bilirəm.|Ihre Auffassung lässt sich anhand der Beispiele gut nachvollziehen.|Her view is easy to understand through the examples.|Onun mövqeyini nümunələr vasitəsilə yaxşı başa düşmək mümkündür.
228,240|Er räumt ein, dass die Kritik weitgehend berechtigt ist.|He admits that the criticism is largely justified.|O, tənqidin böyük ölçüdə haqlı olduğunu etiraf edir.|Sie räumt uns weitgehend freie Hand bei der Planung ein.|She grants us largely free rein in planning.|O, planlaşdırmada bizə böyük ölçüdə sərbəstlik verir.
229,241|Die Autorin hebt den maßgeblichen Beitrag des Teams hervor.|The author highlights the team's decisive contribution.|Müəllif komandanın həlledici töhfəsini vurğulayır.|Ich möchte hervorheben, dass Vertrauen maßgeblich für den Erfolg ist.|I would like to emphasize that trust is crucial to success.|Vurğulamaq istəyirəm ki, etibar uğur üçün həlledicidir.
230,246|Wir wägen die Risiken ab; diese Abwägung braucht Zeit.|We weigh up the risks; this assessment takes time.|Riskləri ölçüb-biçirik; bu qiymətləndirmə vaxt tələb edir.|Eine sorgfältige Abwägung bedeutet, Vor- und Nachteile gegeneinander abzuwägen.|A careful assessment means weighing advantages against disadvantages.|Diqqətli qiymətləndirmə üstünlüklərlə çatışmazlıqları ölçüb-biçmək deməkdir.
231,245|Das Verfahren unterliegt den einschlägigen Regeln.|The procedure is subject to the relevant rules.|Prosedur müvafiq qaydalara tabedir.|Welche Vorgänge unterliegen den einschlägigen Vorschriften?|Which processes are subject to the applicable provisions?|Hansı proseslər müvafiq müddəalara tabedir?
232,242|Dem Projekt geht eine unerlässliche Vorbereitung voraus.|The project is preceded by essential preparation.|Layihədən əvvəl zəruri hazırlıq aparılır.|Eine Prüfung, die der Freigabe vorausgeht, ist unerlässlich.|A check preceding approval is indispensable.|Təsdiqdən əvvəl aparılan yoxlama əvəzolunmazdır.
233,250|Dieses Beispiel verdeutlicht die Tragweite der Entscheidung.|This example illustrates the significance of the decision.|Bu nümunə qərarın əhəmiyyətini aydın göstərir.|Die Lehrerin verdeutlicht uns die Tragweite unseres Handelns.|The teacher makes the implications of our actions clear to us.|Müəllim bizə hərəkətlərimizin nəticələrinin miqyasını aydın göstərir.
234,247|Wir nehmen die örtlichen Gegebenheiten unterschiedlich wahr.|We perceive the local conditions differently.|Biz yerli şəraiti fərqli qavrayırıq.|Wer die Gegebenheiten genau wahrnimmt, kann besser planen.|Someone who perceives the conditions accurately can plan better.|Şəraiti dəqiq qavrayan şəxs daha yaxşı planlaşdıra bilər.
235,243|Der Bericht weist hinreichend Belege auf.|The report contains sufficient evidence.|Hesabatda kifayət qədər sübut var.|Die Lösung muss hinreichende Stabilität aufweisen.|The solution must exhibit sufficient stability.|Həll kifayət qədər sabitliyə malik olmalıdır.
236,244|Das Material ist wiederverwendbar und mithin nachhaltiger.|The material is reusable and thus more sustainable.|Material təkrar istifadə edilə bilər və beləliklə, daha dayanıqlıdır.|Wir sparen Ressourcen und handeln mithin nachhaltig.|We conserve resources and thus act sustainably.|Resurslara qənaət edirik və beləliklə, davamlılığı təmin edirik.
238,239,248|Der Umstand ist bekannt; demnach können wir planen und folglich früher beginnen.|The circumstance is known; accordingly, we can plan and consequently start earlier.|Vəziyyət məlumdur; buna əsasən plan qura və nəticədə daha tez başlaya bilərik.|Demnach hat sich ein wichtiger Umstand geändert; folglich müssen wir den Plan anpassen.|Accordingly, an important circumstance has changed; consequently, we must adjust the plan.|Deməli, mühüm bir hal dəyişib; nəticə etibarilə planı uyğunlaşdırmalıyıq.
`;
const wordExamples = {};
exampleGroups.trim().split('\n').forEach(line => {
  const [ids,de1,en1,az1,de2,en2,az2] = line.split('|');
  ids.split(',').forEach(id => wordExamples[id] = [{de:de1,en:en1,az:az1},{de:de2,en:en2,az:az2}]);
});
